#%RAML 1.0
title: facebook-webhook-poc
mediaType: 
  - application/json
protocols:
  - HTTPS
traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

/callBack:
  /status:
    get:
      is: [client-id-required]
      queryParameters:
        hub.verify_token:
          type: string
          description: 
          example: 
          required: false
        hub.challenge:
          type: string
          description: 
          example: 
          required: false
        hub.mode:
          type: string
          description: 
          example: 
          required: false
      responses:
        200:
          body:
            application/json:
              example: 
    
  /webhook:
    post:
      description: 
      is: [client-id-required]
      body:
        application/json:
      responses:
        200:
          body:
            application/json: